# -*- coding: utf-8 -*-
"""ListaWhile-GustavoBueno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13SgsIgMqNHvA-G_tvJtY11DsKlEwMCP6

Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

#ler uma nota de 0 a 10
#mostre uma msg caso seja invalido
#continuar pedindo até ser valido

while True:
  nota = int(input('Digite a nota de 0 a 10: '))
  if nota <0 or nota >10:
    print('valor invalido')
  else:
    print('valor valido!')
    break

"""Faça um programa que calcule o mostre a média aritmética de N notas.

"""

#calcular media aritmetica
notas = 0
contador = 0
continuar = 'S'


while continuar == 'S':
  nota = float(input('Insira a primeira nota: '))
  contador += 1
  notas += nota
  continuar = input('Deseja continuar? Sim (S), ou não (qlqr tecla): ').upper()

media = notas/contador
print(f'sua média é {media: .2f}')

""" Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.

"""

#ler o usuario e senha
#não aceite a senha igual a do usuario
while True:
  usuario = str(input('cadastre seu usuario: '))
  senha = str(input('cadastre sua senha: '))
  if usuario == senha:
    print('Sua senha não pode ser igual a de seu usuario!')
  else:
    print('cadastrado!')
    break

""" Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

#contratado em 1995
#salario inicial de R$ 1000
#em 1996 salario aumenta 1,5%
#prox ano dobra o valor do %
ano = 0
contador = 1995
percentual = 0.015

salario = int(input('Digite o salario inicial do funcionário: '))

while True:
    print(f'Salario em {contador + ano} = {salario: .2f}')
    ano +=1
    aumento = salario * percentual
    salario += aumento
    percentual *=2
    if contador + ano == 2025:
      break

"""Faça um programa que leia e valide as seguintes informações:
 Nome: maior que 3 caracteres;
 Idade: entre 0 e 150;
 Salário: maior que zero;
 Sexo: 'f' ou 'm';
 Estado Civil: 's', 'c', 'v', 'd'
"""

while True:
  nome = str(input('insira seu nome: '))
  if len(nome) <=3:
    print('Seu nome precisa ter mais que 3 caracteres.')
    continue
  idade = int(input('insira sua idade: '))
  if idade <=0 or idade >150:
    print('idade invalida.')
    continue
  salario = float(input('informe seu salario: '))
  if salario <=0:
    print('seu salario deve ser maior que zero. ')
    continue
  sexo = str(input('informe seu sexo (f para feminino ou m para masculino): '))
  if sexo not in {'m','f'}:
    print('m ou f')
    continue
  ec = str(input('informe seu estado civil: s de solteiro, c de casado, v de viuvo ou d de divorciado: '))
  if ec not in {'s','c', 'v', 'd'}:
    print('s, c, v ou d.')
    continue
  else:
    print(f'cadastrado: {nome}, {idade} anos, salario de R${salario}, sexo: {sexo}, estado civi: {ec}')
    break

"""Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

#paisA 80000 habitantes, taxa anual de 3%
#paisB 200000 habitantes, taxa anual de 1,5%
#paisA ultrapassar paisB
ano = 0
paisa = 80000
paisb = 200000
percentual1 = 0.03
percetual2 = 0.015
while True:
  ano += 1
  aumento1 = paisa * percentual1
  aumento2 = paisb * percentual2
  paisa += aumento1
  paisb += aumento2
  print(f'ano {ano}: pais A: {paisa: .0f}, pais B: {paisb: .0f}')
  if paisa > paisb:
    break

""" Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120

"""

#ler um numero inteiro
#fazer o fatorial

num = int(input('digite um número inteiro para ser fatorado: '))
fatorial = 1
x = 1
while x <= num:
  fatorial = fatorial * x
  x += 1
print(fatorial)

"""Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

#solicite números indefinidamente
#até ele pedir 0
#calcule a média
inteiro = 0
num2 = 0

while True:
  if num != 0:
    num2 += num
  num = int(input('digite numeros, quando vc digitar 0, vou fazer a média de todos eles: '))
  inteiro += 1
  if num == 0:
    inteiro -=1
    print(f'o resultado da média é: {num2 / inteiro}')

"""A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
programa capaz de gerar a série até o n−ésimo termo.
"""

ultimo = 1
penultimo = 1
cont = 1
print(ultimo)
print(penultimo)
while cont <= 9:
  termo = ultimo + penultimo
  penultimo = ultimo
  ultimo = termo
  cont += 1
  print(termo)

""". O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.
 O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.
 O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra.
 A saída deve ser conforme o exemplo abaixo:
 Lojas Tabajara
 Produto 1: R$ 2.20
 Produto 2: R$ 5.80
 Produto 3: R$ 0
 Total: R$ 9.00
 Dinheiro: R$ 20.00
 Troco: R$ 11.00

"""

preco = 0
dinheiro = 0
troco = 0
produto = 0
print('Lojas Tabajara')
while True:
  produto += 1
  mercadoria = float(input(f'produto {produto}: (digite 0 para terminar a compra): '))
  preco += mercadoria
  if mercadoria == 0:
    troco += preco
    print(f'valor total: {preco} R$.')
    din = float(input('qual seria o valor em dinheiro?(maior que o preco da mercadoria, obvio): '))
    dinheiro += din
    if preco >=0:
      print('lojas Tabajara')
      print(f'Total: R${preco:.2f}')
      print(f'Troco: R${dinheiro - preco:.2f}')
      break

""" O cardápio de uma lanchonete é o seguinte:
Especificação Código Preço
 Cachorro Quente 100 R$ 1,20
 Bauru Simples 101 R$ 1,30
 Bauru com ovo 102 R$ 1,50
 Hambúrguer 103 R$ 1,20
 Cheeseburguer 104 R$ 1,30
 Refrigerante 105 R$ 1,00
Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

preço1 = 0
preço2 = 0
preço3 = 0
preço4 = 0
total100 = 0
total101 = 0
total102 = 0
total105 = 0
print('''

    Produto                   codigo   Preco
    -----------------------------------------
    Cachorro Quente            100    R$1.20
    Bauru Simples              101    R$1.30
    Bauru com ovo              102    R$1.50
    Hamburguer                 103    R$1.20
    Cheeseburguer              104    R$1.30
    Refrigerante               105    R$1.00
'''
)
while True:
  pedido = int(input('digite o codigo do produto desejado: (digite 0 se terminou o pedido)  '))
  if pedido == 100 or pedido == 103:
     preço1 += 1.2
     qnt1 = int(input('informe a quantidade: '))
     if qnt1 >= 1:
      qnt_total1 = qnt1
      total1 = preço1 * qnt_total1
      total100 += total1
  if pedido == 101 or pedido == 104:
    preço2 += 1.3
    qnt2 = int(input('informe a quantidade: '))
    if qnt2 >= 1:
      qnt_total2 = qnt2
      total2 = preço2 * qnt_total2
      total101 += total2
  if pedido == 102:
    preço3 += 1.5
    qnt3 = int(input('informe a quantidade: '))
    if qnt3 >= 1:
      qnt_total3 = qnt3
      total3 = preço3 * qnt_total3
      total102 += total3
  if pedido == 105:
    preço4 += 1.0
    qnt4 = int(input('informe a quantidade: '))
    if qnt4 >= 1:
      qnt_total4 = qnt4
      total4 = preço4 * qnt_total4
      total105 += total4
  if pedido == 0:
    total_max = (total100 + total101 + total102 + total105)
    print(f'o total foi de {total_max: .2f}')
    break

""" Em uma eleição presidencial existem quatro candidatos. Os votos são informados
por meio de código.
Os códigos utilizados são:
 1, 2, 3, 4 - Votos para os respectivos candidatos
 (você deve montar a tabela ex: 1 - Jose/ 2- João/etc)
 5 - Voto Nulo
 6 - Voto em Branco
Faça um programa que calcule e mostre:
 O total de votos para cada candidato;
 O total de votos nulos;
 O total de votos em branco;
 A percentagem de votos nulos sobre o total de votos;
 A percentagem de votos em branco sobre o total de votos.
Para finalizar o conjunto de votos tem-se o valor zero.
"""

voto1 = 0
voto2 = 0
voto3 = 0
voto4 = 0
voto5 = 0
voto6 = 0

print('''
Eleições 2024. candidatos:
1- Alexandre
2- Hugo
3- Joao
4- pericles
5- Nulo
6- Branco
''')

while True :
  votacao = int(input('digite em quem voce ira votar:(digite 0 para encerrar as votações)  '))
  if votacao > 6:
    print('Voto invalido')
  if votacao == 1:
    voto1 += 1
  elif votacao == 2:
    voto2 +=1
  elif votacao == 3:
    voto3 +=1
  elif votacao == 4:
    voto4 +=1
  elif votacao == 5:
    voto5 +=1
  elif votacao == 6:
    voto6 +=1
  if votacao == 0:
    break


votos_finais = voto1 + voto2 + voto3 + voto4 + voto5 + voto6
percentagem1 = (voto5/votos_finais) * 100
percentagem2 = (voto6/votos_finais) * 100
print(f'''votos:
1 = {voto1} votos
2 = {voto2} votos
3 = {voto3} votos
4 = {voto4} votos
Nulo (5) = {voto5} votos.
Branco (6) = {voto6} votos.




''')
print(f'porcentagem de votos nulos: {percentagem1:.0f}% ')
print(f'pocentagem de votos em branco {percentagem2:.0f}% ')